### ISSUE TITLE
Phase 2 removemain

### ISSUE THREAD

**Issue by OskarBo** [tum-i22/macke#12]
Is there a reason why the main function is removed from the Klee runs in Phase 2?

In my opinion, the output of MACKE should be the input to the main/entry function which causes a crash of the program under test. If you remove the main function from the Klee run in phase 2 you only get the error chain starting in depth=1 of the program under test.

Maybe there is something I am not seeing, but in my opinion the following would be correct in file Macke.py (line 392):
`        runs = self.callgraph.group_independent_calls(
            removemain=False)`
instead of the current:
`        runs = self.callgraph.group_independent_calls(
            removemain=not bool(self.posix4main))`

**Comment by saahil** [comment]
Please see the function `list_symbolic_encapsulable` in CallGraph.py. `main` function is not removed by default unless explicitly asked to do so. The reason for this special encapsulation of `main` function is that there can only be one `main` function in the program and that `main` function is always the test "runner" in Macke. As a result, we first need to rename the program's original main function to `__macke_main` before proceeding.
