### ISSUE TITLE
Macke phase one fails at simple KLEE example

### ISSUE THREAD

**Issue by fkilger** [tum-i22/macke#2]
When executing macke on the first KLEE example get_sign.c (http://klee.github.io/resources/get_sign.c) I get following output/error:

Start analysis of get_sign.bc in /tmp/macke/2018-03-22-11-43-56
Phase 1: 2 of 5 functions are suitable for symbolic encapsulation
Phase 1: Adding new entry points ... done
Phase 1: Performing KLEE runs ...
  0% (0 of 2) |                                                   | Elapsed Time: 0:00:00 ETA:  --:--:--

A thread in phase one throws and exception
A thread in phase one throws and exception
The analyzed function was: main
The analyzed function was: get_sign
[Errno 2] No such file or directory: '/tmp/macke/2018-03-22-11-43-56/klee/klee-out-2/output.txt'
[Errno 2] No such file or directory: '/tmp/macke/2018-03-22-11-43-56/klee/klee-out-1/output.txt'
  0% (0 of 2) |                                                    | Elapsed Time: 0:04:19 ETA:  --:--:--

Directory /tmp/macke/2018-03-22-11-43-56/klee was created, but empty.

**Comment by saahil** [comment]
Seems like there was a permissions issue with creating the file there.
